[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "8080"

[environments.production.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
replicas = 1
