services:
  - type: web
    name: sixfb-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://sixfb-backend.onrender.com/api/v1
      - key: NEXT_PUBLIC_APP_URL
        value: https://sixfb-frontend.onrender.com