version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 6fb-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/6fb_booking.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-key-change-this}
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - backend-data:/app/data
      - backend-logs:/app/logs
    depends_on:
      - redis
    networks:
      - 6fb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 6fb-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - 6fb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: 6fb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - 6fb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: 6fb-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - 6fb-network
    restart: unless-stopped

networks:
  6fb-network:
    driver: bridge

volumes:
  backend-data:
  backend-logs:
  redis-data:
  nginx-logs: