version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://sixfb-backend.onrender.com/api/v1
      - NEXT_PUBLIC_USE_CORS_PROXY=false
      - NEXT_PUBLIC_ENVIRONMENT=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
