# Railway deployment configuration for 6FB Booking Platform

# Frontend service configuration
[build]
builder = "NIXPACKS"
buildCommand = "cd backend-v2/frontend-v2 && npm install && npm run build"

[deploy]
startCommand = "cd backend-v2/frontend-v2 && node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
ENVIRONMENT = "production"

# Railway provides PORT automatically
# Frontend environment variables should be set in Railway dashboard
