# Railway deployment configuration for 6FB Booking Platform
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
ENVIRONMENT = "production"
WORKERS = "2"
DB_POOL_SIZE = "20"

# Railway will automatically detect this is a Python app
# and set up the environment accordingly