# Railway deployment configuration for 6FB Booking Platform - Backend
[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ENVIRONMENT = "production"
WORKERS = "2"
DB_POOL_SIZE = "20"
PYTHONPATH = "/app/backend"

# Railway provides DATABASE_URL automatically if you have a database service
# PORT is automatically provided by Railway
