# Render.com deployment configuration for 6FB Booking Platform
# This file configures both backend and frontend services

services:
  # Backend API Service
  - type: web
    name: 6fb-booking-backend
    runtime: python-3.11
    region: oregon
    plan: starter # Options: starter ($7/month), standard ($25/month), pro ($85/month)
    buildCommand: cd backend && ./render-build.sh
    startCommand: cd backend && gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --keep-alive 5 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: 6fb-booking-frontend
          property: host
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: 6fb-booking-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false  # Set manually in Render dashboard
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false  # Set manually in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false  # Set manually in Render dashboard
      - key: STRIPE_CONNECT_CLIENT_ID
        sync: false  # Set manually in Render dashboard
      - key: SENDGRID_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: FROM_EMAIL
        sync: false  # Set manually in Render dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false  # Set manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false  # Set manually in Render dashboard
      - key: GOOGLE_CALENDAR_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: info
      - key: CORS_ALLOWED_ORIGINS
        value: https://sixfb-frontend.onrender.com,http://localhost:3000
      - key: MAX_WORKERS
        value: "2"
      - key: WEB_CONCURRENCY
        value: "2"
      # Performance optimization settings
      - key: POOL_SIZE
        value: "10"
      - key: MAX_OVERFLOW
        value: "20"
      - key: POOL_PRE_PING
        value: "true"
      - key: POOL_RECYCLE
        value: "3600"
      # Security settings
      - key: SECURE_COOKIES
        value: "true"
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_HTTPONLY
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: "lax"
    healthCheckPath: /health
    autoDeploy: true  # Auto-deploy enabled for continuous deployment
    # Performance configurations
    numInstances: 1  # Increase for horizontal scaling
    # Additional Render settings
    dockerCommand: ""  # Use default

  # Frontend Next.js Application
  - type: web
    name: 6fb-booking-frontend
    runtime: node
    region: oregon
    plan: starter # Options: starter ($7/month), standard ($25/month)
    buildCommand: |
      cd frontend && \
      npm ci && \
      npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://sixfb-backend.onrender.com
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false  # Set manually in Render dashboard
      - key: NEXT_PUBLIC_GA_TRACKING_ID
        sync: false  # Set manually in Render dashboard
      - key: PORT
        value: 3000
      # Next.js optimization
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      # Build cache optimization
      - key: NEXT_PUBLIC_DISABLE_SPEEDY
        value: "false"
    healthCheckPath: /
    autoDeploy: true  # Auto-deploy enabled for continuous deployment
    # Performance configurations
    numInstances: 1  # Increase for horizontal scaling

# Database
databases:
  - name: 6fb-booking-db
    databaseName: sixfb_booking
    user: sixfb_user
    region: oregon
    plan: starter  # $7/month - upgrade to standard ($22/month) for production
    ipAllowList: []  # Allow connections from all IPs (Render services)
    # Database optimizations
    postgresMajorVersion: 15  # Latest stable version

# Redis Cache (Optional but recommended for production)
# Uncomment to enable Redis caching
# - name: 6fb-booking-redis
#   type: redis
#   region: oregon
#   plan: starter  # $7/month
#   maxmemoryPolicy: allkeys-lru  # Least recently used eviction
#   ipAllowList: []  # Allow connections from Render services
