# Enhanced Auto-Fixer Configuration

# Notification Settings
notifications:
  slack:
    enabled: true
    webhook_url: ${SLACK_WEBHOOK_URL}
    channels:
      errors: "#sentry-errors"
      fixes: "#auto-fixes"

  email:
    enabled: true
    recipients:
      - "dev-team@6fbmentorship.com"
      - "support@6fbmentorship.com"
    send_on:
      - "fix_failed"
      - "high_risk_error"
      - "manual_review_required"
      - "weekly_summary"

# Rate Limiting
rate_limits:
  fixes_per_minute: 10
  fixes_per_hour: 50
  fixes_per_day: 200

  # Per error type limits
  by_type:
    database_schema: 5  # Max 5 DB fixes per hour
    authentication: 10
    api_rate_limit: 20

# Circuit Breaker
circuit_breaker:
  failure_threshold: 5
  timeout_seconds: 60
  half_open_tests: 3

# Error Grouping
error_grouping:
  similarity_threshold: 0.85
  group_timeout_minutes: 5
  max_group_size: 10

# Health Monitoring
health_monitoring:
  check_interval_seconds: 60
  error_spike_threshold: 2.0  # 2x baseline
  rollback_on_spike: true
  metrics_window_minutes: 5

# Pattern Learning
pattern_learning:
  min_samples_for_confidence: 10
  disable_threshold: 30  # Disable if confidence < 30%
  confidence_calculation: "bayesian"  # bayesian or frequency

  # Confidence thresholds for auto-fix
  auto_fix_thresholds:
    safe: 85
    review: 60
    manual: 0

# Performance Monitoring
performance:
  baseline_update_interval: 3600  # 1 hour
  alert_on_degradation: true
  degradation_threshold: 1.5  # 50% slower

  endpoints_to_monitor:
    - "/api/v1/appointments"
    - "/api/v1/barbers"
    - "/api/v1/payments"

# Database Migration Settings
migrations:
  auto_generate: true
  require_approval: true
  safe_operations:
    - "add_column"
    - "add_index"
    - "create_table"

  unsafe_operations:
    - "drop_column"
    - "drop_table"
    - "rename_column"

# Approval Workflows
approvals:
  required_for:
    - risk_level: "HIGH"
    - confidence_below: 70
    - error_types: ["database_schema", "authentication"]

  approval_methods:
    - "slack_interactive"
    - "github_pr"
    - "email_link"

  timeout_hours: 24

# Integration Settings
integrations:
  github:
    enabled: true
    create_prs: true
    auto_merge_confidence: 95
    reviewers:
      - "@dev-team"

  jira:
    enabled: false
    create_tickets: true
    project: "AUTOFIX"

  pagerduty:
    enabled: false
    integration_key: ${PAGERDUTY_KEY}

# Error Type Configurations
error_types:
  database_schema:
    auto_fixable: true
    max_retries: 3
    notification_priority: "high"
    requires_migration: true

  authentication:
    auto_fixable: true
    max_retries: 2
    notification_priority: "medium"
    requires_restart: false

  api_rate_limit:
    auto_fixable: true
    max_retries: 5
    notification_priority: "low"
    backoff_strategy: "exponential"

  import_error:
    auto_fixable: true
    max_retries: 2
    notification_priority: "medium"

  timeout:
    auto_fixable: false
    max_retries: 1
    notification_priority: "high"

  connection_error:
    auto_fixable: false
    max_retries: 3
    notification_priority: "high"

# Weekly Report Settings
reporting:
  enabled: true
  schedule: "0 9 * * MON"  # Every Monday at 9 AM
  recipients:
    - "team-lead@6fbmentorship.com"
    - "cto@6fbmentorship.com"

  include:
    - total_fixes
    - success_rate
    - top_error_types
    - pattern_confidence_scores
    - performance_impact
    - cost_savings_estimate
