#!/bin/bash
echo "=== Create Admin User for 6FB Platform ==="
echo ""
echo "Since direct database connection from local is having issues, here are your options:"
echo ""
echo "OPTION 1: Use the API directly (Recommended)"
echo "----------------------------------------"
echo "1. First, temporarily create a simple admin user by SSH-ing into Render:"
echo "   - Go to your Render backend service"
echo "   - Click 'Shell' tab"
echo "   - Run these commands:"
echo ""
echo "python3 -c \""
echo "from models.user import User"
echo "from models.base import Base"
echo "from passlib.context import CryptContext"
echo "from sqlalchemy import create_engine"
echo "from sqlalchemy.orm import sessionmaker"
echo "import os"
echo ""
echo "DATABASE_URL = os.getenv('DATABASE_URL')"
echo "engine = create_engine(DATABASE_URL)"
echo "SessionLocal = sessionmaker(bind=engine)"
echo "db = SessionLocal()"
echo ""
echo "pwd_context = CryptContext(schemes=['bcrypt'], deprecated='auto')"
echo "hashed = pwd_context.hash('Welcome123!')"
echo ""
echo "admin = User("
echo "    email='c50bossio@gmail.com',"
echo "    first_name='Chris',"
echo "    last_name='Bossio',"
echo "    hashed_password=hashed,"
echo "    role='super_admin',"
echo "    is_active=True,"
echo "    is_verified=True,"
echo "    permissions=['*']"
echo ")"
echo "db.add(admin)"
echo "db.commit()"
echo "print('Admin user created!')"
echo "\""
echo ""
echo "OPTION 2: Use these credentials"
echo "--------------------------------"
echo "Email: c50bossio@gmail.com"
echo "Password: Welcome123!"
echo ""
echo "IMPORTANT: Change this password after first login!"
echo ""
echo "To login to the API docs:"
echo "1. Go to: https://sixfb-backend.onrender.com/docs"
echo "2. Click 'Authorize' button"
echo "3. Enter the email and password above"
