services:
  - type: web
    name: 6fb-booking-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 6fb-booking-db
          property: connectionString
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: CORS_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://6fb-booking-backend.onrender.com/api/v1/google-calendar/callback
    buildCommand: echo "Build complete"
    startCommand: ./start-render.sh

databases:
  - name: 6fb-booking-db
    databaseName: sixfb_booking
    user: sixfb_user
    plan: starter
