#!/usr/bin/env python3
"""
Generate Trafft integration configuration
"""
import secrets

def generate_webhook_secret():
    """Generate a secure webhook secret"""
    return secrets.token_urlsafe(32)

def main():
    # Known values
    backend_url = "https://sixfb-backend.onrender.com"
    webhook_url = f"{backend_url}/api/v1/webhooks/trafft"
    
    # Generate webhook secret
    webhook_secret = generate_webhook_secret()
    
    print("\n=== 6FB Platform - Trafft Integration Configuration ===\n")
    
    print("📋 STEP 1: Get your Trafft API Key")
    print("-" * 50)
    print("1. Log into your Trafft admin panel")
    print("2. Navigate to: Settings → Integrations → API")
    print("3. Generate or copy your API key")
    print("4. Note your subdomain (e.g., 'yourbusiness' from yourbusiness.trafft.com)\n")
    
    print("🔧 STEP 2: Add Environment Variables to Render")
    print("-" * 50)
    print("Go to your backend service on Render and add these environment variables:\n")
    print(f"TRAFFT_API_URL=https://api.trafft.com")
    print(f"TRAFFT_API_KEY=<YOUR_TRAFFT_API_KEY>")
    print(f"TRAFFT_WEBHOOK_SECRET={webhook_secret}")
    print("\n(Copy the webhook secret above - it's been generated securely for you)\n")
    
    print("🔗 STEP 3: Webhook Information")
    print("-" * 50)
    print(f"Your webhook URL: {webhook_url}")
    print("(Trafft will send events to this URL)\n")
    
    print("🚀 STEP 4: Complete the Integration")
    print("-" * 50)
    print("After adding the environment variables and redeploying:\n")
    print("1. Access the API documentation:")
    print(f"   {backend_url}/docs")
    print("\n2. Authenticate with your admin credentials")
    print("\n3. Use these endpoints in order:")
    print("   a. POST /api/trafft/connect - Connect with your API key")
    print("   b. POST /api/trafft/webhooks/register - Register webhooks")
    print("   c. POST /api/trafft/sync/initial - Import existing data")
    print("\n4. Verify integration:")
    print("   GET /api/trafft/status - Check connection status")
    print("   GET /api/trafft/webhooks/status - Check webhook status\n")
    
    print("📝 STEP 5: Testing")
    print("-" * 50)
    print("1. Create a test appointment in Trafft")
    print("2. Check if it appears in your 6FB dashboard")
    print("3. Monitor webhook logs in Render for debugging\n")
    
    # Save configuration
    config_content = f"""# Trafft Integration Configuration
# Generated by trafft_setup_config.py

# Your Backend URLs
BACKEND_URL={backend_url}
WEBHOOK_URL={webhook_url}
API_DOCS_URL={backend_url}/docs

# Environment Variables for Render
# IMPORTANT: Replace <YOUR_TRAFFT_API_KEY> with your actual API key!
TRAFFT_API_URL=https://api.trafft.com
TRAFFT_API_KEY=<YOUR_TRAFFT_API_KEY>
TRAFFT_WEBHOOK_SECRET={webhook_secret}

# API Endpoints for Integration
CONNECT_ENDPOINT=POST {backend_url}/api/v1/api/trafft/connect
REGISTER_WEBHOOKS_ENDPOINT=POST {backend_url}/api/v1/api/trafft/webhooks/register
INITIAL_SYNC_ENDPOINT=POST {backend_url}/api/v1/api/trafft/sync/initial
STATUS_ENDPOINT=GET {backend_url}/api/v1/api/trafft/status
WEBHOOK_STATUS_ENDPOINT=GET {backend_url}/api/v1/api/trafft/webhooks/status

# cURL Examples (replace YOUR_6FB_TOKEN with your actual auth token)
# Connect:
curl -X POST {backend_url}/api/v1/api/trafft/connect \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer YOUR_6FB_TOKEN" \\
  -d '{{"api_key": "YOUR_TRAFFT_API_KEY"}}'

# Register Webhooks:
curl -X POST {backend_url}/api/v1/api/trafft/webhooks/register \\
  -H "Authorization: Bearer YOUR_6FB_TOKEN"

# Initial Sync:
curl -X POST {backend_url}/api/v1/api/trafft/sync/initial \\
  -H "Authorization: Bearer YOUR_6FB_TOKEN"
"""
    
    with open("trafft_integration_config.txt", "w") as f:
        f.write(config_content)
    
    print("✅ Configuration saved to: trafft_integration_config.txt")
    print("⚠️  IMPORTANT: Keep this file secure and don't commit it to git!\n")

if __name__ == "__main__":
    main()