databases:
  - name: sixfb-db
    databaseName: sixfb
    user: sixfb
    plan: free

services:
  - type: web
    name: sixfb-backend-v2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sixfb-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
  
  - type: web
    name: sixfb-frontend-v2
    runtime: node
    plan: free
    buildCommand: cd frontend-v2 && npm install && npm run build
    startCommand: cd frontend-v2 && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://sixfb-backend-v2.onrender.com
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
    rootDir: .
    healthCheckPath: /