apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookedbarber-backend
  namespace: bookedbarber-v2
  labels:
    app: bookedbarber-backend
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookedbarber-backend
  template:
    metadata:
      labels:
        app: bookedbarber-backend
    spec:
      initContainers:
      - name: migrate-database
        image: bookedbarber/backend:latest
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: bookedbarber-config
        - secretRef:
            name: bookedbarber-secrets
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bookedbarber-secrets
              key: DATABASE_URL
      containers:
      - name: backend
        image: bookedbarber/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: bookedbarber-config
        - secretRef:
            name: bookedbarber-secrets
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  name: bookedbarber-backend-service
  namespace: bookedbarber-v2
  labels:
    app: bookedbarber-backend
spec:
  selector:
    app: bookedbarber-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bookedbarber-backend-hpa
  namespace: bookedbarber-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookedbarber-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max