apiVersion: v1
kind: ConfigMap
metadata:
  name: bookedbarber-config
  namespace: bookedbarber-production
data:
  # Database Configuration
  DATABASE_HOST: "postgresql-primary.bookedbarber-production.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "bookedbarber_production"
  
  # Redis Configuration
  REDIS_HOST: "redis-master.bookedbarber-production.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Application Configuration
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "info"
  
  # External Services
  STRIPE_API_VERSION: "2024-06-20"
  SENDGRID_API_VERSION: "v3"
  
  # Performance Settings
  WORKERS: "4"
  MAX_CONNECTIONS: "100"
  POOL_SIZE: "20"
  POOL_TIMEOUT: "30"
  
  # Security Settings
  ALLOWED_HOSTS: "bookedbarber.com,*.bookedbarber.com"
  CORS_ORIGINS: "https://bookedbarber.com,https://app.bookedbarber.com"
  SECURE_COOKIES: "true"
  CSRF_PROTECTION: "true"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  
  # Monitoring
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookedbarber-frontend-config
  namespace: bookedbarber-production
data:
  # Next.js Configuration
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  
  # API Configuration
  NEXT_PUBLIC_API_URL: "https://api.bookedbarber.com"
  NEXT_PUBLIC_APP_URL: "https://app.bookedbarber.com"
  
  # Stripe Configuration (Public Keys)
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_live_..."
  
  # Analytics Configuration
  NEXT_PUBLIC_GA_TRACKING_ID: "G-XXXXXXXXXX"
  NEXT_PUBLIC_SENTRY_DSN: "https://xxx@sentry.io/xxx"
  
  # Feature Flags
  NEXT_PUBLIC_FEATURE_ANALYTICS: "true"
  NEXT_PUBLIC_FEATURE_NOTIFICATIONS: "true"
  NEXT_PUBLIC_FEATURE_CALENDAR_SYNC: "true"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookedbarber-staging-config
  namespace: bookedbarber-staging
data:
  # Database Configuration
  DATABASE_HOST: "postgresql-staging.bookedbarber-staging.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "bookedbarber_staging"
  
  # Redis Configuration
  REDIS_HOST: "redis-staging.bookedbarber-staging.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  
  # Application Configuration
  ENVIRONMENT: "staging"
  DEBUG: "true"
  LOG_LEVEL: "debug"
  
  # External Services (Test Keys)
  STRIPE_API_VERSION: "2024-06-20"
  SENDGRID_API_VERSION: "v3"
  
  # Performance Settings
  WORKERS: "2"
  MAX_CONNECTIONS: "50"
  POOL_SIZE: "10"
  POOL_TIMEOUT: "30"
  
  # Security Settings
  ALLOWED_HOSTS: "staging.bookedbarber.com,*.staging.bookedbarber.com"
  CORS_ORIGINS: "https://staging.bookedbarber.com"
  SECURE_COOKIES: "true"
  CSRF_PROTECTION: "true"
  
  # Rate Limiting (More Lenient)
  RATE_LIMIT_REQUESTS: "200"
  RATE_LIMIT_WINDOW: "60"
  
  # Monitoring
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"