[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "8080"
NEXT_PUBLIC_API_URL = "https://sixfb-backend-v2.onrender.com"
NEXT_PUBLIC_APP_URL = "https://app.bookedbarber.com"
NEXT_PUBLIC_DEMO_MODE = "false"
NEXT_PUBLIC_ENVIRONMENT = "production"

[environments.production.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
replicas = 1