# BookedBarber V2 - Production Security Configuration
# Comprehensive security hardening for production environment
# Last updated: 2025-07-23

# Security Headers Configuration
security_headers:
  # HTTP Strict Transport Security (HSTS)
  hsts:
    enabled: true
    max_age: 31536000  # 1 year
    include_subdomains: true
    preload: true
    
  # Content Security Policy (CSP)
  content_security_policy:
    enabled: true
    policy: |
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://js.stripe.com 
        https://checkout.stripe.com
        https://www.googletagmanager.com
        https://connect.facebook.net;
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com;
      font-src 'self' 
        https://fonts.gstatic.com;
      img-src 'self' data: https: 
        https://www.google-analytics.com
        https://www.facebook.com;
      connect-src 'self' 
        https://api.stripe.com
        https://www.google-analytics.com
        https://graph.facebook.com;
      frame-src 'self' 
        https://js.stripe.com 
        https://hooks.stripe.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    report_uri: "/api/v2/security/csp-report"
    
  # X-Frame-Options
  x_frame_options:
    enabled: true
    value: "DENY"
    
  # X-Content-Type-Options
  x_content_type_options:
    enabled: true
    value: "nosniff"
    
  # X-XSS-Protection
  x_xss_protection:
    enabled: true
    value: "1; mode=block"
    
  # Referrer Policy
  referrer_policy:
    enabled: true
    value: "strict-origin-when-cross-origin"
    
  # Permissions Policy
  permissions_policy:
    enabled: true
    policy: |
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(self),
      usb=(),
      magnetometer=(),
      gyroscope=(),
      accelerometer=()

# Rate Limiting Configuration
rate_limiting:
  # Global rate limits
  global:
    requests_per_minute: 60
    requests_per_hour: 1000
    requests_per_day: 10000
    
  # Endpoint-specific rate limits
  endpoints:
    # Authentication endpoints (stricter limits)
    "/api/v2/auth/login":
      requests_per_minute: 5
      requests_per_hour: 20
      lockout_duration: 300  # 5 minutes
      
    "/api/v2/auth/register":
      requests_per_minute: 3
      requests_per_hour: 10
      
    "/api/v2/auth/forgot-password":
      requests_per_minute: 2
      requests_per_hour: 5
      
    # Payment endpoints (critical protection)
    "/api/v2/payments/*":
      requests_per_minute: 10
      requests_per_hour: 100
      
    # Booking endpoints
    "/api/v2/appointments":
      requests_per_minute: 20
      requests_per_hour: 200
      
    # Public endpoints (more generous)
    "/api/v2/public/*":
      requests_per_minute: 100
      requests_per_hour: 1000
      
  # IP-based blocking
  ip_blocking:
    enabled: true
    block_duration: 3600  # 1 hour
    max_violations: 5
    whitelist:
      - "127.0.0.1"
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"

# Input Validation & Sanitization
input_validation:
  # SQL Injection Prevention
  sql_injection:
    enabled: true
    parameterized_queries_only: true
    sql_keywords_blacklist:
      - "DROP"
      - "DELETE"
      - "TRUNCATE"
      - "ALTER"
      - "CREATE"
      - "EXEC"
      - "UNION"
      - "SCRIPT"
    
  # XSS Prevention
  xss_protection:
    enabled: true
    html_sanitization: true
    javascript_encoding: true
    css_sanitization: true
    
  # File Upload Security
  file_uploads:
    enabled: true
    max_file_size: 10485760  # 10MB
    allowed_extensions:
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
      - ".pdf"
    virus_scanning: true
    content_type_validation: true
    
  # API Input Validation
  api_validation:
    max_request_size: 1048576  # 1MB
    json_depth_limit: 10
    array_length_limit: 1000
    string_length_limit: 10000

# Authentication & Authorization Security
auth_security:
  # Password Security
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    prevent_common_passwords: true
    password_history: 12  # Remember last 12 passwords
    
  # Session Management
  session_security:
    secure_cookies: true
    httponly_cookies: true
    samesite_cookies: "Strict"
    session_timeout: 1800  # 30 minutes
    absolute_timeout: 28800  # 8 hours
    rotate_session_id: true
    
  # JWT Security
  jwt_security:
    algorithm: "HS256"
    access_token_expiry: 900  # 15 minutes
    refresh_token_expiry: 604800  # 7 days
    issuer: "bookedbarber.com"
    audience: "bookedbarber-api"
    
  # Multi-Factor Authentication
  mfa:
    enabled: true
    required_for_admin: true
    required_for_payment: false  # Optional for better UX
    backup_codes: 10
    totp_issuer: "BookedBarber"
    
  # Account Lockout
  account_lockout:
    enabled: true
    max_failed_attempts: 5
    lockout_duration: 1800  # 30 minutes
    progressive_delays: true

# Data Protection & Privacy
data_protection:
  # Encryption at Rest
  encryption_at_rest:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
  # Encryption in Transit
  encryption_in_transit:
    tls_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    
  # PII Protection
  pii_protection:
    field_encryption:
      - "social_security_number"
      - "credit_card_number"
      - "bank_account_number"
    field_masking:
      - "phone_number"
      - "email_address"
    data_retention_days: 2555  # 7 years for financial records
    
  # GDPR Compliance
  gdpr_compliance:
    enabled: true
    data_export: true
    data_deletion: true
    consent_tracking: true
    breach_notification: true

# API Security
api_security:
  # API Authentication
  authentication:
    require_authentication: true
    api_key_auth: false  # Use JWT instead
    oauth2_scopes:
      - "read:appointments"
      - "write:appointments"
      - "read:profile"
      - "write:profile"
      - "admin:users"
      
  # API Versioning Security
  versioning:
    deprecated_versions:
      - "v1"  # Mark v1 as deprecated
    version_sunset_date: "2025-12-31"
    
  # CORS Security
  cors:
    allowed_origins:
      - "https://bookedbarber.com"
      - "https://www.bookedbarber.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "X-Requested-With"
    credentials: true
    max_age: 86400  # 24 hours

# Network Security
network_security:
  # Firewall Rules
  firewall:
    enabled: true
    default_policy: "deny"
    rules:
      - port: 443
        protocol: "tcp"
        action: "allow"
        source: "0.0.0.0/0"
      - port: 80
        protocol: "tcp"
        action: "allow"
        source: "0.0.0.0/0"
      - port: 22
        protocol: "tcp"
        action: "allow"
        source: "10.0.0.0/8"  # Internal only
        
  # DDoS Protection
  ddos_protection:
    enabled: true
    threshold_requests_per_second: 100
    threshold_concurrent_connections: 1000
    mitigation_actions:
      - "rate_limit"
      - "challenge"
      - "block"
      
  # Geographic Blocking
  geo_blocking:
    enabled: false  # Disable for global accessibility
    blocked_countries: []
    
  # IP Reputation
  ip_reputation:
    enabled: true
    block_known_bad_ips: true
    threat_intelligence_feeds:
      - "spamhaus"
      - "malwaredomainlist"

# Security Monitoring & Alerting
security_monitoring:
  # Security Events
  events:
    - name: "Multiple failed login attempts"
      threshold: 5
      time_window: 300  # 5 minutes
      severity: "high"
      
    - name: "Suspicious payment activity"
      conditions:
        - "amount > 10000"
        - "frequency > 10 per hour"
      severity: "critical"
      
    - name: "Admin account access"
      conditions:
        - "role = admin"
        - "login_time = outside_business_hours"
      severity: "medium"
      
    - name: "Data export requests"
      conditions:
        - "endpoint = /api/v2/data/export"
      severity: "medium"
      
  # Anomaly Detection
  anomaly_detection:
    enabled: true
    machine_learning: true
    baseline_period_days: 30
    sensitivity: "medium"
    
  # Security Dashboards
  dashboards:
    - name: "Security Overview"
      metrics:
        - "failed_login_attempts"
        - "blocked_requests"
        - "security_violations"
        - "suspicious_activities"
        
    - name: "Threat Intelligence"
      metrics:
        - "ip_reputation_blocks"
        - "malware_detections"
        - "vulnerability_scans"

# Vulnerability Management
vulnerability_management:
  # Dependency Scanning
  dependency_scanning:
    enabled: true
    scan_frequency: "daily"
    auto_update_patch_level: true
    vulnerability_databases:
      - "CVE"
      - "NVD"
      - "Snyk"
      
  # Code Security Scanning
  code_scanning:
    static_analysis: true
    dynamic_analysis: true
    secrets_detection: true
    scan_on_commit: true
    
  # Infrastructure Scanning
  infrastructure_scanning:
    container_scanning: true
    configuration_scanning: true
    network_scanning: true
    scan_frequency: "weekly"

# Incident Response
incident_response:
  # Security Incident Classification
  incident_classification:
    p0_critical:
      - "data_breach"
      - "payment_system_compromise"
      - "admin_account_takeover"
      
    p1_high:
      - "unauthorized_access"
      - "malware_detection"
      - "ddos_attack"
      
    p2_medium:
      - "suspicious_activity"
      - "policy_violation"
      - "vulnerability_disclosure"
  
  # Response Teams
  response_teams:
    security_team:
      - "security@bookedbarber.com"
      - "cto@bookedbarber.com"
      
    legal_team:
      - "legal@bookedbarber.com"
      - "privacy@bookedbarber.com"
      
    communications_team:
      - "pr@bookedbarber.com"
      - "support@bookedbarber.com"
  
  # Response Procedures
  procedures:
    containment:
      - "isolate_affected_systems"
      - "preserve_evidence"
      - "notify_stakeholders"
      
    eradication:
      - "remove_threat"
      - "patch_vulnerabilities"
      - "update_security_controls"
      
    recovery:
      - "restore_from_backup"
      - "monitor_for_reoccurrence"
      - "validate_security_posture"

# Compliance & Auditing
compliance:
  # Audit Logging
  audit_logging:
    enabled: true
    log_retention_days: 2555  # 7 years
    events_to_log:
      - "authentication_attempts"
      - "authorization_failures"
      - "data_access"
      - "configuration_changes"
      - "administrative_actions"
      - "payment_transactions"
      
  # Compliance Frameworks
  frameworks:
    - name: "PCI DSS"
      version: "4.0"
      requirements:
        - "secure_network"
        - "protect_cardholder_data"
        - "maintain_vulnerability_program"
        - "implement_access_controls"
        - "monitor_networks"
        - "maintain_information_security_policy"
        
    - name: "GDPR"
      requirements:
        - "lawful_basis"
        - "data_minimization"
        - "consent_management"
        - "breach_notification"
        - "data_subject_rights"
        
  # Regular Security Assessments
  assessments:
    penetration_testing:
      frequency: "annually"
      scope: "full_application"
      
    vulnerability_assessments:
      frequency: "quarterly"
      scope: "infrastructure_and_application"
      
    compliance_audits:
      frequency: "annually"
      frameworks: ["PCI_DSS", "GDPR"]

# Security Training & Awareness
security_training:
  # Developer Security Training
  developer_training:
    secure_coding_practices: true
    owasp_top_10: true
    threat_modeling: true
    frequency: "quarterly"
    
  # Security Awareness
  awareness_program:
    phishing_simulations: true
    security_newsletters: true
    incident_case_studies: true
    frequency: "monthly"

# Backup & Disaster Recovery Security
backup_security:
  # Backup Encryption
  encryption:
    enabled: true
    algorithm: "AES-256"
    key_management: "external"
    
  # Backup Access Controls
  access_controls:
    role_based_access: true
    multi_person_authorization: true
    audit_all_access: true
    
  # Disaster Recovery Testing
  dr_testing:
    frequency: "quarterly"
    scope: "full_system"
    rto: 4  # hours
    rpo: 1  # hour

# Third-Party Security
third_party_security:
  # Vendor Risk Assessment
  vendor_assessment:
    security_questionnaires: true
    penetration_test_reports: true
    compliance_certifications: true
    
  # API Integration Security
  api_integrations:
    stripe:
      webhook_signature_verification: true
      ip_whitelist: true
      rate_limiting: true
      
    google:
      oauth_scope_minimization: true
      token_rotation: true
      
    sendgrid:
      api_key_rotation: true
      sending_limits: true