"""sync database schema with current models

Revision ID: 8f33e6d146fa
Revises: 42921896b92c
Create Date: 2025-07-05 10:04:50.890580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8f33e6d146fa'
down_revision: Union[str, Sequence[str], None] = '42921896b92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversion_events_campaign'), table_name='conversion_events')
    op.drop_index(op.f('idx_conversion_events_channel_date'), table_name='conversion_events')
    op.drop_index(op.f('idx_conversion_events_type_date'), table_name='conversion_events')
    op.drop_index(op.f('idx_conversion_events_user_date'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_channel'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_client_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_event_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_event_name'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_event_type'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_session_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_user_id'), table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_index(op.f('idx_conversion_goals_user_active'), table_name='conversion_goals')
    op.drop_index(op.f('ix_conversion_goals_id'), table_name='conversion_goals')
    op.drop_index(op.f('ix_conversion_goals_user_id'), table_name='conversion_goals')
    op.drop_table('conversion_goals')
    op.drop_index(op.f('ix_tracking_configurations_id'), table_name='tracking_configurations')
    op.drop_table('tracking_configurations')
    op.drop_index(op.f('idx_campaign_tracking_active'), table_name='campaign_tracking')
    op.drop_index(op.f('idx_campaign_tracking_dates'), table_name='campaign_tracking')
    op.drop_index(op.f('ix_campaign_tracking_campaign_id'), table_name='campaign_tracking')
    op.drop_index(op.f('ix_campaign_tracking_id'), table_name='campaign_tracking')
    op.drop_index(op.f('ix_campaign_tracking_user_id'), table_name='campaign_tracking')
    op.drop_table('campaign_tracking')
    op.drop_index(op.f('ix_attribution_paths_id'), table_name='attribution_paths')
    op.drop_index(op.f('ix_attribution_paths_user_id'), table_name='attribution_paths')
    op.drop_table('attribution_paths')
    op.drop_index(op.f('ix_short_urls_id'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_short_code'), table_name='short_urls')
    op.drop_table('short_urls')
    op.alter_column('organizations', 'tracking_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'true'"))
    op.alter_column('organizations', 'organization_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'independent'"))
    op.alter_column('staff_invitations', 'email_send_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_staff_invitations_organization'), table_name='staff_invitations')
    op.drop_index(op.f('idx_staff_invitations_status'), table_name='staff_invitations')
    op.create_index(op.f('ix_staff_invitations_id'), 'staff_invitations', ['id'], unique=False)
    op.alter_column('user_organizations', 'can_manage_billing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_organizations', 'can_manage_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_organizations', 'can_view_analytics',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'role_migrated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_users_unified_role'), 'users', ['unified_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_unified_role'), table_name='users')
    op.alter_column('users', 'role_migrated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_organizations', 'can_view_analytics',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_organizations', 'can_manage_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user_organizations', 'can_manage_billing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_staff_invitations_id'), table_name='staff_invitations')
    op.create_index(op.f('idx_staff_invitations_status'), 'staff_invitations', ['status'], unique=False)
    op.create_index(op.f('idx_staff_invitations_organization'), 'staff_invitations', ['organization_id'], unique=False)
    op.alter_column('staff_invitations', 'email_send_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('organizations', 'organization_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'independent'"))
    op.alter_column('organizations', 'tracking_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'true'"))
    op.create_table('short_urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('original_url', sa.TEXT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('click_count', sa.INTEGER(), nullable=True),
    sa.Column('last_clicked', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_short_code'), 'short_urls', ['short_code'], unique=1)
    op.create_index(op.f('ix_short_urls_id'), 'short_urls', ['id'], unique=False)
    op.create_table('attribution_paths',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('conversion_event_id', sa.INTEGER(), nullable=False),
    sa.Column('touchpoints', sqlite.JSON(), nullable=False),
    sa.Column('first_touch_channel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_touch_channel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('path_length', sa.INTEGER(), nullable=True),
    sa.Column('attribution_model', sa.VARCHAR(length=14), nullable=True),
    sa.Column('attribution_weights', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversion_event_id'], ['conversion_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversion_event_id')
    )
    op.create_index(op.f('ix_attribution_paths_user_id'), 'attribution_paths', ['user_id'], unique=False)
    op.create_index(op.f('ix_attribution_paths_id'), 'attribution_paths', ['id'], unique=False)
    op.create_table('campaign_tracking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('campaign_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('campaign_source', sa.VARCHAR(length=50), nullable=False),
    sa.Column('campaign_medium', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('impressions', sa.INTEGER(), nullable=True),
    sa.Column('clicks', sa.INTEGER(), nullable=True),
    sa.Column('conversions', sa.INTEGER(), nullable=True),
    sa.Column('conversion_value', sa.FLOAT(), nullable=True),
    sa.Column('ctr', sa.FLOAT(), nullable=True),
    sa.Column('conversion_rate', sa.FLOAT(), nullable=True),
    sa.Column('cpc', sa.FLOAT(), nullable=True),
    sa.Column('cpa', sa.FLOAT(), nullable=True),
    sa.Column('roas', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_sync_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'campaign_id', 'campaign_source', name=op.f('uq_user_campaign'))
    )
    op.create_index(op.f('ix_campaign_tracking_user_id'), 'campaign_tracking', ['user_id'], unique=False)
    op.create_index(op.f('ix_campaign_tracking_id'), 'campaign_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_tracking_campaign_id'), 'campaign_tracking', ['campaign_id'], unique=False)
    op.create_index(op.f('idx_campaign_tracking_dates'), 'campaign_tracking', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('idx_campaign_tracking_active'), 'campaign_tracking', ['user_id', 'is_active'], unique=False)
    op.create_table('tracking_configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('gtm_container_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gtm_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('gtm_server_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('meta_pixel_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('meta_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('meta_test_event_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('google_ads_conversion_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('google_ads_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('google_ads_conversion_labels', sqlite.JSON(), nullable=True),
    sa.Column('attribution_window_days', sa.INTEGER(), nullable=True),
    sa.Column('view_attribution_window_days', sa.INTEGER(), nullable=True),
    sa.Column('default_attribution_model', sa.VARCHAR(length=14), nullable=True),
    sa.Column('conversion_value_rules', sqlite.JSON(), nullable=True),
    sa.Column('excluded_domains', sqlite.JSON(), nullable=True),
    sa.Column('custom_channel_rules', sqlite.JSON(), nullable=True),
    sa.Column('enable_enhanced_conversions', sa.BOOLEAN(), nullable=True),
    sa.Column('hash_user_data', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tracking_configurations_id'), 'tracking_configurations', ['id'], unique=False)
    op.create_table('conversion_goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('value_expression', sa.TEXT(), nullable=True),
    sa.Column('conditions', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('total_conversions', sa.INTEGER(), nullable=True),
    sa.Column('total_value', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name=op.f('uq_user_goal_name'))
    )
    op.create_index(op.f('ix_conversion_goals_user_id'), 'conversion_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversion_goals_id'), 'conversion_goals', ['id'], unique=False)
    op.create_index(op.f('idx_conversion_goals_user_active'), 'conversion_goals', ['user_id', 'is_active'], unique=False)
    op.create_table('conversion_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('event_value', sa.FLOAT(), nullable=True),
    sa.Column('event_currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('event_data', sqlite.JSON(), nullable=True),
    sa.Column('source_url', sa.TEXT(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('utm_source', sa.VARCHAR(length=255), nullable=True),
    sa.Column('utm_medium', sa.VARCHAR(length=255), nullable=True),
    sa.Column('utm_campaign', sa.VARCHAR(length=255), nullable=True),
    sa.Column('utm_term', sa.VARCHAR(length=255), nullable=True),
    sa.Column('utm_content', sa.VARCHAR(length=255), nullable=True),
    sa.Column('referrer', sa.TEXT(), nullable=True),
    sa.Column('gtm_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('gtm_sync_time', sa.DATETIME(), nullable=True),
    sa.Column('meta_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('meta_sync_time', sa.DATETIME(), nullable=True),
    sa.Column('google_ads_synced', sa.BOOLEAN(), nullable=True),
    sa.Column('google_ads_sync_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_events_user_id'), 'conversion_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_session_id'), 'conversion_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_id'), 'conversion_events', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_events_event_type'), 'conversion_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_conversion_events_event_name'), 'conversion_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_conversion_events_event_id'), 'conversion_events', ['event_id'], unique=1)
    op.create_index(op.f('ix_conversion_events_client_id'), 'conversion_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_channel'), 'conversion_events', ['channel'], unique=False)
    op.create_index(op.f('idx_conversion_events_user_date'), 'conversion_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_conversion_events_type_date'), 'conversion_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('idx_conversion_events_channel_date'), 'conversion_events', ['channel', 'created_at'], unique=False)
    op.create_index(op.f('idx_conversion_events_campaign'), 'conversion_events', ['utm_campaign', 'created_at'], unique=False)
    # ### end Alembic commands ###
