name: 6fb-platform
region: nyc
features:
  - buildpack-stack=ubuntu-22

services:
  - name: backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 10
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.REDIS_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "0!%zSPydOb$&IKiVMF7CIKxc3%VnAEKpWzERl#UK3XpitWW#yAt!j2TAIs1^^OYW"
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: SMTP_HOST
        scope: RUN_TIME
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        scope: RUN_TIME
        value: "587"
      - key: SMTP_USERNAME
        scope: RUN_TIME
        value: apikey
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "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"
      - key: EMAIL_FROM_NAME
        scope: RUN_TIME
        value: "Chris Bossio - 6FB Mentorship"
      - key: EMAIL_FROM_ADDRESS
        scope: RUN_TIME
        value: support@em3014.6fbmentorship.com
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: https://6fbmentorship.com
      - key: BACKEND_CORS_ORIGINS
        scope: RUN_TIME
        value: "https://6fbmentorship.com,https://www.6fbmentorship.com"

  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: ${backend.PUBLIC_URL}

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1

  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-dev-database
    num_nodes: 1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE