apiVersion: v1
kind: Namespace
metadata:
  name: bookedbarber-staging
  labels:
    name: bookedbarber-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookedbarber-production
  labels:
    name: bookedbarber-production
    environment: production