{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookedbarber.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bookedbarber.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: {{ include "bookedbarber.databaseUrl" . | quote }}
  POSTGRES_USER: {{ .Values.secrets.database.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.password | quote }}
  POSTGRES_DB: {{ .Values.secrets.database.name | quote }}
  
  # Redis connection
  REDIS_URL: {{ include "bookedbarber.redisUrl" . | quote }}
  
  # JWT signing key
  JWT_SECRET_KEY: {{ .Values.secrets.jwt.secretKey | quote }}
  
  # Stripe configuration
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripe.secretKey | quote }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.secrets.stripe.publishableKey | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripe.webhookSecret | quote }}
  
  # Email service (SendGrid)
  SENDGRID_API_KEY: {{ .Values.secrets.sendgrid.apiKey | quote }}
  
  # SMS service (Twilio)
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilio.accountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilio.authToken | quote }}
  
  # Google services
  GOOGLE_CLIENT_ID: {{ .Values.secrets.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.google.clientSecret | quote }}
  
  # Monitoring (Sentry)
  SENTRY_DSN: {{ .Values.secrets.sentry.dsn | quote }}
  NEXT_PUBLIC_SENTRY_DSN: {{ .Values.secrets.sentry.publicDsn | quote }}
  
  {{- if .Values.monitoring.grafana.enabled }}
  # Grafana admin password
  GRAFANA_ADMIN_PASSWORD: {{ .Values.monitoring.grafana.adminPassword | quote }}
  {{- end }}
{{- end }}